apiVersion: apps/v1             # API version
kind: Deployment                # Type of kubernetes resource
metadata:
  name: polling-app-client      # Name of the kubernetes resource
  namespace: public
spec:
  replicas: 1                   # No of replicas/pods to run
  selector:                     
    matchLabels:                # This deployment applies to Pods matching the specified labels
      app: polling-app-client
  template:                     # Template for creating the Pods in this deployment
    metadata:
      labels:                   # Labels that will be applied to all the Pods in this deployment
        app: polling-app-client
    spec:                       # Spec for the containers that will run inside the Pods
      containers:
      - name: polling-app-client
        image: 899456967600.dkr.ecr.us-east-2.amazonaws.com/spring-frontend:8c665c2amd64
        imagePullPolicy: IfNotPresent
        env:
          - name: REACT_APP_API_BASE_URL
            value: https://polling-api.verticalrelevancelabs.com
        ports:
          - name: http
            containerPort: 80   # Should match the Port that the container listens on
              #jkresources:
              #jk  limits:
              #jk    cpu: 0.2
              #jk    memory: "10Mi"
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: polling-app-client      # Name of the kubernetes resource
  namespace: public
spec:
  type: NodePort                # Exposes the service by opening a port on each node
  selector:
    app: polling-app-client     # Any Pod matching the label `app=polling-app-client` will be picked up by this service
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polling-app-client
  namespace: public
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:899456967600:certificate/e0e84eda-6739-4ab4-a65d-db7247a64d4d
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: polling.verticalrelevancelabs.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: polling-app-client
              port:
                number: 80
